"""The ``?analytics=on`` dashboard. Read-only; reset only behind a password."""

from __future__ import annotations

from typing import Any, Callable, Dict, Optional

import altair as alt
import pandas as pd
import streamlit as st

from . import aggregate, utils
from .state import data  # noqa: F401


def show_results(
    data: Dict[str, Any],  # noqa: F811
    reset_callback: Callable[[], None],
    unsafe_password: Optional[str] = None,
    store: Any = None,
) -> None:
    """Show analytics results in streamlit, asking for password if given."""
    st.title("Analytics Dashboard")
    st.markdown("""
        Psst! 👀 You found a secret section generated by
        [streamlit-analytics2](https://github.com/444B/streamlit-analytics2).
        If you didn't mean to go here, remove `?analytics=on` from the URL.
        """)

    show = True
    if unsafe_password is not None:
        password_input = st.text_input(
            "Enter password to show results", type="password"
        )
        if password_input != unsafe_password:
            show = False
            if len(password_input) > 0:
                st.write("Nope, that's not correct ☝️")
    if not show:
        return

    summary = None
    if store is not None:
        try:
            summary = aggregate.summarize(store.read())
        except Exception as exc:
            st.warning(f"Could not read the event log: {exc}")

    st.header("Traffic")
    st.write(f"since {data['start_time']}")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric(
        "Pageviews",
        data["total_pageviews"],
        help="Every time a user (re-)loads the site.",
    )
    col2.metric(
        "Script runs",
        data["total_script_runs"],
        help="Every time Streamlit reruns upon changes or interactions.",
    )
    col3.metric(
        "Time spent",
        utils.format_seconds(data["total_time_seconds"]),
        help="Total usage from all users from run to last widget interaction",
    )
    if summary:
        col4.metric(
            "Sessions / visitors",
            f"{summary['sessions']} / {summary['visitors']}",
            help="Browser sessions, and distinct visitors per day (hashed, rotates daily).",
        )
    st.write("")

    _traffic_chart(data)

    if summary:
        if summary["pages"]:
            st.header("Pages")
            st.dataframe(pd.DataFrame(summary["pages"]), hide_index=True)
        st.header("Widget interactions")
        st.markdown(
            "One row per widget (type, label, key). A change is counted only "
            "when a user acts, never on first render. Free text is not stored "
            "unless `store_values=True`."
        )
        if summary["widgets"]:
            st.dataframe(pd.DataFrame(summary["widgets"]), hide_index=True)
        else:
            st.caption("No widget interactions recorded yet.")
        if summary["custom"]:
            st.header("Custom events")
            st.dataframe(pd.DataFrame(summary["custom"]), hide_index=True)
        if summary["avg_session_seconds"]:
            st.caption(
                f"Average session length {utils.format_seconds(summary['avg_session_seconds'])} "
                f"over {summary['events']} events."
            )

    with st.expander("Legacy counters (`streamlit_analytics2.data`)"):
        _legacy_widgets(data)

    if unsafe_password is not None:
        st.header("Danger zone")
        with st.expander("Here be dragons 🐲🔥"):
            st.write("""
                Reset all analytics results. **This erases everything tracked so
                far, including results synced to Firestore.** The event log file
                is not touched.
                """)
            reset_prompt = st.selectbox(
                "Continue?",
                [
                    "No idea what I'm doing here",
                    "I'm sure that I want to reset the results",
                ],
            )
            if reset_prompt == "I'm sure that I want to reset the results":
                if st.button("Click here to reset"):
                    reset_callback()
                    st.write("Done! Please refresh the page.")


def _traffic_chart(data: Dict[str, Any]) -> None:  # noqa: F811
    df = pd.DataFrame(data["per_day"])
    if df.empty:
        return
    x_axis = (
        "yearmonthdate(days):O"
        if pd.to_datetime(df["days"]).dt.year.nunique() > 1
        else "monthdate(days):O"
    )
    base = alt.Chart(df).encode(x=alt.X(x_axis, axis=alt.Axis(title="", grid=True)))
    line1 = base.mark_line(point=True, stroke="#5276A7").encode(
        alt.Y(
            "pageviews:Q",
            axis=alt.Axis(
                titleColor="#5276A7",
                tickColor="#5276A7",
                labelColor="#5276A7",
                format=".0f",
                tickMinStep=1,
            ),
            scale=alt.Scale(domain=(0, int(df["pageviews"].max()) + 1)),
        )
    )
    line2 = base.mark_line(point=True, stroke="#57A44C").encode(
        alt.Y(
            "script_runs:Q",
            axis=alt.Axis(
                title="script runs",
                titleColor="#57A44C",
                tickColor="#57A44C",
                labelColor="#57A44C",
                format=".0f",
                tickMinStep=1,
            ),
        )
    )
    layer = (
        alt.layer(line1, line2)
        .resolve_scale(y="independent")
        .configure_axis(titleFontSize=15, labelFontSize=12, titlePadding=10)
    )
    st.altair_chart(layer, width="stretch")


def _legacy_widgets(data: Dict[str, Any]) -> None:  # noqa: F811
    if not data.get("widgets"):
        st.caption("Nothing yet.")
        return
    for name, counts in data["widgets"].items():
        st.markdown(f"##### `{name}`")
        if isinstance(counts, dict):
            st.dataframe(
                pd.DataFrame(
                    {
                        "selected_value": list(counts.keys()),
                        "number_of_interactions": list(counts.values()),
                    }
                ).sort_values(by="number_of_interactions", ascending=False),
                hide_index=True,
            )
        else:
            st.write(f"{counts} interactions")
