[streamlit_analytics2]
enabled = "true"

[storage]
save = "false"
type = "json"
save_to_json = "path/to/file.json"
load_from_json = "path/to/file.json"

[logs]
verbose = "false"

[access]
unsafe_password = "test123"

[firestore]
enabled = "false"
firestore_key_file = "firebase-key.json" 
firestore_project_name= ""
firestore_collection_name = "data"
streamlit_secrets_firestore_key = ""

[session]
session_id = ""
