[streamlit_analytics2]
enabled = true

[storage]
save = true
type = "csv"
path = "sa2_data/analytics_data.json"

[access]
password_hash = "f6e0a1e2ac41945a9aa7ff8a8aaa0cebc12a3bcc981a929ad5cf810a090e11ae"
require_auth = true

[setup]
completed = true
version = "0.11.0"
